### ISSUE TITLE
Error when creating subvention

### ISSUE THREAD

**Issue by Maurice67205** [treytux/trey-addons#7]
Dear all when trying to configure a subvention with Odoo 12 Community I get the following error Odoo Server (see attached screen shots, could not upload a video)
![Step3](https://user-images.githubusercontent.com/11387919/74513134-31ae5f80-4f0a-11ea-9a7d-35ca140f7f86.png)
![Step2](https://user-images.githubusercontent.com/11387919/74513136-32df8c80-4f0a-11ea-9161-dca0629f0c4d.png)
![Step 1](https://user-images.githubusercontent.com/11387919/74513139-32df8c80-4f0a-11ea-9a64-b9f91adfd251.png)

Regards
Maurice

**Comment by cubells** [comment]
@Maurice67205 can you paste the last lines that are not seen in first capture where you click on "Voire les détails"?

Thanks.

**Comment by Maurice67205** [comment]
@cubells here you go



Odoo Server Error

Traceback (most recent call last):
  File "/home/tempo/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/tempo/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/tempo/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/tempo/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/tempo/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/tempo/odoo12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/tempo/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/tempo/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/tempo/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/tempo/odoo12/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/tempo/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/tempo/odoo12/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/home/tempo/odoo12/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/tempo/odoo12/odoo/models.py", line 1644, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/home/tempo/odoo12/addons/account/models/account.py", line 204, in _name_search
    account_ids = self._search(expression.AND([domain, args]), limit=limit, access_rights_uid=name_get_uid)
  File "/home/tempo/odoo12/odoo/models.py", line 4110, in _search
    query = self._where_calc(args)
  File "/home/tempo/odoo12/odoo/models.py", line 3902, in _where_calc
    e = expression.expression(domain, self)
  File "/home/tempo/odoo12/odoo/osv/expression.py", line 673, in __init__
    self.parse()
  File "/home/tempo/odoo12/odoo/osv/expression.py", line 854, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'type' in leaf "<osv.ExtendedLeaf: ('type', '!=', 'view') on account_account (ctx: )>"

**Comment by rlizana** [comment]
Hi @Maurice67205 , I have uploaded a few changes to solve the problem, please try it.

**Comment by Maurice67205** [comment]
HI @rlizana , I can now create a subvention but don't understand how the whole thing works
Attached is my subvention and an invoice related to it but I don't see anything registrered
Regards
Maurice 
![Subvention](https://user-images.githubusercontent.com/11387919/74648755-92de6900-517e-11ea-977f-e380dc57a064.png)
![Invoice](https://user-images.githubusercontent.com/11387919/74648765-95d95980-517e-11ea-9e0f-d0061b186937.png)
